pipeline {
    agent any
    environment {
        VENV = ".venv"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Info') {
            steps {
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
            }
        }

        stage('Lint') {
            agent {
                docker {
                    image 'python:3.11-slim'
                    args '-u 0:0'
                }
            }
            steps {
                sh '''
                    apt-get update && apt-get install -y make
                    python -m venv .venv
                    .venv/bin/pip install --upgrade pip
                    .venv/bin/pip install -r requirements.txt
                    .venv/bin/pip install flake8
                    make lint || true
                '''
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'python:3.11-slim'
                    args '-u 0:0'
                }
            }
            steps {
                sh '''
                    .venv/bin/pip install -r requirements.txt
                    make test
                '''
            }
        }
    }
    post {
        always {
            junit '**/test-reports/*.xml' // Si pytest genera XML
            archiveArtifacts artifacts: 'coverage*.xml, coverage_html/**/*', allowEmptyArchive: true
        }
        success {
            echo "Pipeline finished successfully!"
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}



