pipeline {
    agent any

    stages {
        stage('Info') {
            steps {
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'python:3.6-slim'
                }
            }
            steps {
                sh 'python --version'
                sh 'echo "Stage dummy. Aquí ejecutarás los tests unitarios."'
            }
        }
    }
}
